version: "3"

services:
  vpn-server:
    image: ubuntu:22.04

    container_name: vpn-server

    restart: unless-stopped

    ports:
      - "51820:51820/udp"

    command: tail -f /dev/null
  node-exporter:
    image: prom/node-exporter

    container_name: node-exporter

    restart: unless-stopped

    ports:
      - "9100:9100"
