name: CI

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate Repository
        run: echo "Validation completed"
